[package]
name = "glubhs"
version = "0.1.0"
authors = ["Maria Lucia Gubolin <mlgubolin@protonmail.com>"]

[[bin]]
name = "glubhs"
path = "src/main.rs"

[dependencies]
multiarray = "0.1.3"
cip_rust = "0.9.8"